##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.1

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user

 # - page: rss
 #   directory: atom.xml
#icon: fa-rss

# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

# Toc
toc:
  enable: true
  number: false

# Static files
js: js
css: css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus:  road100 ## disqus_shortname
  livere: ## 来必力(data-uid)
  uyan:  ## 友言(uid)
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: ## 畅言(appid)
    appkey: ##畅言(appkey)

#Share
#baidu_share: true ## 百度分享
#JiaThis_share: ##true ##JiaThis分享
#duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
#addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
#  - twitter
#  - baidu
#  - facebook
#  - google_plus
#  - linkedin
#  - email

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics:  b9d8fedcf143fea0dadf2f9779ef2ecd## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true. 

# About page
about:
  photo_url: https://img1.doubanio.com/view/photo/l/public/p2519803238.webp ## Your            photo e.g. http://obzf7z93c.bkt.clouddn.com/themeauthor.jpg
  items:
  - label: email
    url: road037019@gmail.com ## Your email with mailto: e.g.  mailto:zhenggchaoo@gmail.com
    title: road10@163.com ## Your email e.g.  zhenggchaoo@gmail.com
  - label: github
    url: https://github.com/road037019 ## Your github'url e.g.  https://github.com/chaooo
    title: My_Github ## Your github'name e.g.  chaooo
  - label: weibo
    url: https://weibo.com/5388232868/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1 ## Your weibo's url e.g.  http://weibo.com/zhengchaooo
    title: 十一月zz ## Your weibo's name e.g.  秋过冬漫 
  - label: CSDN
    url: https://blog.csdn.net/baidu_35679960
    title: 十一月zz的博客
  - label: 豆瓣
    url:  https://www.douban.com/people/164337430/
    title:  我的豆瓣
# Links widget. Empty links will hide widget.
links:

  - title: 谷歌搜索
    url: http://www.google.cn/
#  - title: site-name2
#    url: http://www.example2.com/
#  - title: site-name3
#    url: http://www.example3.com/
